### ISSUE TITLE
Enhancement to Team Member Page

### ISSUE THREAD

**Issue by DavidRRice** [UNLV-SPFG/UNLV-SPFG.github.io#21]
I'd like a place to prominently display ORCiD and personal webpage links. My suggestions is to have an additional section on the left side for "Links" after "Research Interests" such as: 

  - title: "Links"
    text: "<ul>
    <li> [ORCiD](....)
    <li> [Personal Website](....)"

The links don't seem to work currently in this environment.

**Comment by sabaronett** [comment]
Found a workaround, @DavidRRice. Markdown is not rendered in the YAML front matter, but HTML tags are (e.g., `<ul>`, `<li>`). So try something like this:
```yaml
---
title: "Avery Bailey"
excerpt: "Postdoctoral Scholar"
header:
  teaser: /assets/images/team/avery-bailey.jpg
sidebar:
  - title: "Position"
    image: /assets/images/team/avery-bailey.jpg
    text: "Postdoctoral Scholar"
  - title: "Research Interests"
    text: "<ul>
    <li> <a href='https://google.com'>Google</a>"
---
```
**Note**: you must use single quotes `'` (i.e., apostrophes) to wrap your target after `href=`—**do not use double-quotes `"`** as this confuses the YAML interpreter with how the existing strings are being wrapped/nested.
